# Generated by Django 6.0.2 on 2026-02-17 22:08

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LAB", "Lab"),
                            ("CLASSROOM", "Classroom"),
                            ("EVENT_HALL", "Event Hall"),
                        ],
                        max_length=20,
                    ),
                ),
                ("capacity", models.IntegerField(default=0)),
                ("total_quantity", models.IntegerField(default=1)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "resource_status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("UNAVAILABLE", "Unavailable"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("AUTO_APPROVE", "Auto Approve"),
                            ("STAFF_APPROVE", "Staff Approve"),
                            ("ADMIN_APPROVE", "Admin Approve"),
                        ],
                        default="AUTO_APPROVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "managed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "resources",
            },
        ),
        migrations.CreateModel(
            name="ResourceAdditionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proposed_name", models.CharField(max_length=200)),
                (
                    "proposed_type",
                    models.CharField(
                        choices=[
                            ("LAB", "Lab"),
                            ("CLASSROOM", "Classroom"),
                            ("EVENT_HALL", "Event Hall"),
                        ],
                        max_length=20,
                    ),
                ),
                ("proposed_capacity", models.IntegerField(default=0)),
                ("proposed_total_quantity", models.IntegerField(default=1)),
                (
                    "proposed_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("proposed_description", models.TextField(blank=True, null=True)),
                (
                    "proposed_approval_type",
                    models.CharField(
                        choices=[
                            ("AUTO_APPROVE", "Auto Approve"),
                            ("STAFF_APPROVE", "Staff Approve"),
                            ("ADMIN_APPROVE", "Admin Approve"),
                        ],
                        default="AUTO_APPROVE",
                        max_length=20,
                    ),
                ),
                ("justification", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="addition_request",
                        to="resources.resource",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_addition_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_resource_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "resource_addition_requests",
            },
        ),
        migrations.CreateModel(
            name="ResourceWeeklySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                ("start_time", models.TimeField(default=datetime.time(8, 0))),
                ("end_time", models.TimeField(default=datetime.time(19, 0))),
                ("is_working", models.BooleanField(default=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_schedules",
                        to="resources.resource",
                    ),
                ),
            ],
            options={
                "db_table": "resource_weekly_schedules",
            },
        ),
        migrations.CreateModel(
            name="CalendarOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("override_date", models.DateField(unique=True)),
                (
                    "override_type",
                    models.CharField(
                        choices=[
                            ("HOLIDAY", "Holiday"),
                            ("WORKING_DAY", "Working Day"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calendar_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "calendar_overrides",
                "indexes": [
                    models.Index(
                        fields=["created_by"], name="calendar_ov_created_db6115_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["type"], name="resources_type_f63025_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["resource_status"], name="resources_resourc_e37cdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["managed_by"], name="resources_managed_52d52b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["is_deleted"], name="resources_is_dele_18238f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourceadditionrequest",
            index=models.Index(
                fields=["requested_by"], name="resource_ad_request_5a08cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourceadditionrequest",
            index=models.Index(fields=["status"], name="resource_ad_status_e16b85_idx"),
        ),
        migrations.AddIndex(
            model_name="resourceweeklyschedule",
            index=models.Index(
                fields=["resource"], name="resource_we_resourc_80cacb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="resourceweeklyschedule",
            unique_together={("resource", "day_of_week")},
        ),
    ]
