# Generated by Django 6.0.2 on 2026-02-17 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "actor_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("target_entity_type", models.CharField(db_index=True, max_length=50)),
                ("target_entity_id", models.BigIntegerField(blank=True, null=True)),
                ("previous_state", models.JSONField(blank=True, null=True)),
                ("new_state", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["target_entity_type", "target_entity_id"],
                        name="audit_logs_target__e2ea9e_idx",
                    ),
                    models.Index(
                        fields=["actor_email"], name="audit_logs_actor_e_f3ef0d_idx"
                    ),
                ],
            },
        ),
    ]
