# Generated by Django 6.0.2 on 2026-02-17 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("BOOKING_APPROVED", "Booking Approved"),
                            ("BOOKING_REJECTED", "Booking Rejected"),
                            ("BOOKING_CANCELLED", "Booking Cancelled"),
                            ("BOOKING_AUTO_CANCELLED", "Booking Auto Cancelled"),
                            ("REGISTRATION_APPROVED", "Registration Approved"),
                            ("REGISTRATION_REJECTED", "Registration Rejected"),
                            ("ROLE_CHANGE_APPROVED", "Role Change Approved"),
                            ("ROLE_CHANGE_REJECTED", "Role Change Rejected"),
                            ("GENERAL", "General"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "related_entity_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("related_entity_id", models.BigIntegerField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_email_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "created_at"],
                        name="user_notifi_user_id_d909fd_idx",
                    ),
                    models.Index(
                        fields=["message_type"], name="user_notifi_message_3ef0e0_idx"
                    ),
                ],
            },
        ),
    ]
